channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.13
  - numpy=1.21.6
  - pandas=1.3.5
  - scipy=1.4.1
  - scikit-learn=1.0.2
  - matplotlib=3.2.2
  - seaborn=0.11.2
  - jupyter=1.0.0
  - missingno=0.4.2
