TARGET = "CURRENT_ENERGY_RATING"

IDS = ["LMK_KEY", "BUILDING_REFERENCE_NUMBER", "POSTCODE"]

DATES = ["INSPECTION_DATE"]

NUMERICAL = [
    "TOTAL_FLOOR_AREA",
    "FLAT_STOREY_COUNT",
    "MULTI_GLAZE_PROPORTION",
    "EXTENSION_COUNT",
    "NUMBER_HABITABLE_ROOMS",
    "NUMBER_HEATED_ROOMS",
    "LOW_ENERGY_LIGHTING",
    "NUMBER_OPEN_FIREPLACES",
    "WIND_TURBINE_COUNT",
    "UNHEATED_CORRIDOR_LENGTH",
    "FLOOR_HEIGHT",
    "FIXED_LIGHTING_OUTLETS_COUNT",
    "LOW_ENERGY_FIXED_LIGHT_COUNT",
]

CATEGORICAL = [
    "CITY",
    "PROPERTY_TYPE",
    "BUILT_FORM",
    "CONSTRUCTION_AGE_BAND",
    "ENERGY_TARIFF",
    "MAINS_GAS_FLAG",
    "FLOOR_LEVEL",
    "FLAT_TOP_STOREY",
    "MAIN_HEATING_CONTROLS",
    "GLAZED_TYPE",
    "GLAZED_AREA",
    "HOTWATER_DESCRIPTION",
    "FLOOR_DESCRIPTION",
    "WINDOWS_DESCRIPTION",
    "WALLS_DESCRIPTION",
    "SECONDHEAT_DESCRIPTION",
    "ROOF_DESCRIPTION",
    "MAINHEAT_DESCRIPTION",
    "MAINHEATCONT_DESCRIPTION",
    "LIGHTING_DESCRIPTION",
    "MAIN_FUEL",
    "HEAT_LOSS_CORRIDOR",
    "SOLAR_WATER_HEATING_FLAG",
    "MECHANICAL_VENTILATION",
]
